server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/backend-api
spring.datasource.username=postgres
spring.datasource.password=LeoTricolor06

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
projeto.jwtSecret=49F22F2FB29AC82D597945F1CDB076798D80A62C0C4AE6D45A5CF2C75709ECDD379231014647E0D4BBB6BF822C269D2E20088ED1856231E6A939D75B5155EB23
projeto.jwtExpirationMs=900000