spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.datasource.password=${DB_PASSWORD}
projeto.jwtSecret=${JWT_SECRET}
spring.mail.password=${MAIL_PASSWORD}
springdoc.swagger-ui.tags-sorter=alpha